version: '3'
services:
  nginx:
    image: nginx:1.19.1
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./data:/usr/share/nginx/html/data
      - ../../dist:/usr/share/nginx/html/data/dist
    ports:
      - 80:80
      - 443:443
